name: Deploy to Test Environment

on:
  push:
    branches:
      - backend-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Change to Go directory
        run: cd go-server

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lancehe/go-simplewms-test:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
