#workflow名称
name: ci
# 触发条件
on:
  push:
    branches:
      - backend-dev
#变量配置      
env:
  #镜像名称
  IMAGE_NAME: go-simplewms-server-test
  #dockerHub仓库名称
  DOCKER_REGISTRY: go-simplewms-test
jobs:
  build-image:
    #运行的环境  
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    outputs:
      tags: ${{ steps.output-id.outputs.v }}
    steps:
      # 拉取代码，同时获取tag，如果获取不到则默认值为edge，并赋值给v变量
      - uses: actions/checkout@v3
      - id: output-id
        run: |
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "v=${VERSION}" >> $GITHUB_OUTPUT
      # Docker配置多平台环境
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      # 登录镜像仓库
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          #这里引用的变量为上一步配置的变量
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      # 打包构建并推送
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./go-server
          dockerfile: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          #推送到镜像仓库  
          push: true
          # 这里会构建两个版本镜像，
          # 1.dweizhao/backend:latest
          # 2.  output-id步骤中获取的v，构建dweizhao/backend:edge或者dweizhao/backend:对应tag值
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.output-id.outputs.v }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest