name: Web Test Environment Deploy

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: install dependencies
          run: | 
            npm install
          working-directory: ./vue-web
        - name: build
          run: |
            npm run build
          working-directory: ./vue-web
        - name: deploy
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            branch: web-deploy
            folder: ./vue-web/dist
